window.onload=function(){var k=localStorage.ids;if(typeof k!="undefined"){console.log(k);k=k.split(",").reverse();console.log(k);for(var m=0,o=k.length;m<o;m++){var n=document.getElementById(k[m]);n.parentNode.insertBefore(n,document.getElementsByClassName("dragable")[0])}}};
for(var titles=document.getElementsByTagName("h2"),i=0,len=titles.length;i<len;i++){titles[i].addEventListener("touchstart",function(){this.className="hover"},false);titles[i].addEventListener("touchend",function(){this.className=""},false)}var links=document.getElementsByTagName("td"),tempClasses,j;j=0;
for(len=links.length;j<len;j++){links[j].addEventListener("touchstart",function(){tempClasses=this.className;this.className="hover"},false);links[j].addEventListener("touchend",function(){this.className=tempClasses},false)}
var getDragClass=function(){var k="createTouch"in document,m=k?"touchmove":"mousemove",o=k?"touchend":"mouseup",n=document.getElementById("topblock").clientHeight+70;$=function(c){var f=[];if(c.substring(0,1)=="#")return document.getElementById(c.split("#")[1]);else{c=document.getElementsByClassName(c.split(".")[1]);for(var g=0,b=c.length;g<b;g++)f.push(c[g])}return f};preventDefault=function(c){if(c)c.preventDefault();else window.event.returnValue=false};getMousePoint=function(c){var f=y=0;c=c.touches.item(0);
f=c.pageX;y=c.pageY;return{x:f,y:y}};addEvent=function(c,f,g,b){c.addEventListener(f,function(e){g(e,b)},false)};function p(c){this.el=typeof c.el=="string"?$(c.el):c.el;this.onstart=c.start||new Function;this.onmove=c.move||new Function;this.onend=c.end||new Function;this.action=false;this.lastY=0;this.placeHolder=null;this.index=0;this.ismove=false;this.init()}p.prototype={init:function(){for(var c=0,f=this.el.length;c<f;c++){var g=this.el[c],b=this;addEvent(g,"touchstart",function(e,h){if(b.action)return false;
else b.action=true;for(var d=0,l=b.el.length;d<l;d++)b.el[d].childNodes[3].style["max-height"]="0";this.ismove=false;b.startPoint=getMousePoint(e);h.style["z-index"]="9999";h.style.position="absolute";b.lastY=h.style.top==""?0:parseInt(h.style.top.substring(0,h.style.top.length-2),10);b.current=h;this.placeHolder=document.createElement("section");this.placeHolder.className="placeHolder";this.placeHolder.style.height="87px";h.parentNode.insertBefore(this.placeHolder,h);b.onstart()},g);addEvent(g,"touchmove",
function(e){preventDefault(e);this.ismove=true;b.nowPoint=getMousePoint(e);console.log(n);b.current.style.top=b.nowPoint.y-n+"px";b._index=(b.nowPoint.y-n)/87+1;if(parseInt(b._index,10)>6){b.current.parentNode.removeChild($(".placeHolder")[0]);b.placeHolder=document.createElement("section");b.placeHolder.className="placeHolder";b.placeHolder.style.height="87px";b.current.parentNode.appendChild(b.placeHolder)}else{b.current.parentNode.removeChild($(".placeHolder")[0]);b.placeHolder=document.createElement("section");
b.placeHolder.className="placeHolder";b.placeHolder.style.height="87px";b.current.parentNode.insertBefore(b.placeHolder,$(".dragable")[parseInt(b._index,10)])}b.onmove()});addEvent(g,"touchend",function(){document["on"+o]=document.ontouchcancel=document["on"+m]=null;if(this.ismove){b.current.parentNode.insertBefore(b.current,$(".dragable")[parseInt(b._index,10)]);var e=[],h=$(".dragable");d=0;for(l=h.length;d<l;d++)e.push(h[d].id);localStorage.ids=e}else{for(var d=0,l=b.el.length;d<l;d++)b.el[d].childNodes[3].style["max-height"]=
"0";b.current.childNodes[3].style["max-height"]="9999px"}this.ismove=false;b.current.style.top="0px";b.current.style.position="relative";e=$(".placeHolder");d=0;for(l=e.length;d<l;d++)b.current.parentNode.removeChild(e[d]);b.current.style["z-index"]="9998";b.index=0;b.action=false;b.onend()});addEvent(g,"touchcancel",function(){document["on"+o]=document.ontouchcancel=document["on"+m]=null;b.current.style["z-index"]="9998";b.action=false;b.onend(obj)})}},bind:function(c,f){return function(){c.apply(f,
arguments)}},tool:null};return function(c){return new p(c)}}(),a=getDragClass({el:".dragable",start:function(){},move:function(){},end:function(){}});
